#
# AppSwitch single-node docker-compose file.
#
# daemon service:
#  docker-compose up -d appswitch
#
# test service:
#  docker-compose up -d test && curl -I <host ip>:10000

version: '2.3'

volumes:
  appswitch_logs:

services:
  appswitch:
    image: appswitch/ax
    pid: "host"
    network_mode: "host"
    privileged: true
    volumes:
      - /usr/bin:/usr/bin
      - /dev:/dev
      - /var/run/appswitch:/var/run/appswitch
      - appswitch_logs:/var/log
    environment:
      - AX_DRIVER=user # Syscall forwarding driver
      - AX_NODE_INTERFACE= # Node interface to use by daemon.  Accepts IP address or interface name, eg eth0
      - AX_NEIGHBORS= # List (csv) of IP addresses of cluster neighbors
      - AX_CLUSTER= # Cluster name.  Required if cluster is part of a federation
      - AX_FEDERATION_GATEWAY_IP= # IP address or `interface` name for federation connectivity
      - AX_FEDERATION_GATEWAY_NEIGHBORS= # List (`csv`) of IP addresses of federation neighbors (other gateway nodes)
      - AX_OPTS=--clean # Remove any saved state from previous sessions

  test:
    image: python:alpine
    entrypoint: /usr/bin/ax run --ip 1.1.1.1 --expose 8000:0.0.0.0:10000 --new-netns=false --dns-override=false
    command: python -m http.server
    networks: []
    volumes:
      - /usr/bin:/usr/bin
      - /var/run/appswitch:/var/run/appswitch
    depends_on:
      - appswitch
